CC=gcc
CFLAGS=-Wall
all: task2_part1 task2_part2 task2_part4

task2_part1: task2_part1.c
	gcc -Wall -o task2_part1 task2_part1.c
task2_part2: task2_part2.c
	gcc -Wall -o task2_part2 task2_part2.c
task2_part4: task2_part4.c
	gcc -Wall -o task2_part4 task2_part4.c
	
.PHONY: clean all
clean:
	rm task2_part1 task2_part2 task2_part4