CC=gcc
CFLAGS=-Wall
all: task_part1 task_part2 task_part3 task_part4 task_part5

task_part1:task_part1.c
	gcc -Wall -o task_part1 task_part1.c
task_part2:task_part2.c
	gcc -Wall -o task_part2 task_part2.c
task_part3:task_part3.c
	gcc -Wall -o task_part3 task_part3.c			
task_part4:task_part4.c
	gcc -Wall -o task_part4 task_part4.c
task_part5:task_part5.c
	gcc -Wall -o task_part5 task_part5.c

.PHONY: clean all
clean:
	rm task_part1 task_part2 task_part3 task_part4 task_part5 